// Code generated by MockGen. DO NOT EDIT.
// Source: notes_repository.go

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	gomock "github.com/golang/mock/gomock"
)

// MockNotesRepository is a mock of NotesRepository interface.
type MockNotesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotesRepositoryMockRecorder
}

// MockNotesRepositoryMockRecorder is the mock recorder for MockNotesRepository.
type MockNotesRepositoryMockRecorder struct {
	mock *MockNotesRepository
}

// NewMockNotesRepository creates a new mock instance.
func NewMockNotesRepository(ctrl *gomock.Controller) *MockNotesRepository {
	mock := &MockNotesRepository{ctrl: ctrl}
	mock.recorder = &MockNotesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotesRepository) EXPECT() *MockNotesRepositoryMockRecorder {
	return m.recorder
}
